files:

#####  Context : EmppgmContext #####

# Datasources descriptions. Each datasource contains following parameters :
# name : the datasource identifier (if null or empty, set as default datasource)
# driver : the driver to use (mandatory)
# url : the url (mandatory)
# urlSuffix : the url suffix (optional)

datasources:

# Programs descriptions. Each program can define it's own datasources or refer to "datasources:".
programs:
